@baseUrl = http://localhost:3001/v1/typeUsers

### GET
GET {{baseUrl}}

### POST /typeUsers
POST {{baseUrl}}
Content-Type: application/json

{
  "Name": "Pollo"
}

### UPDATE /typeUsers
PATCH  {{baseUrl}}/3
Content-Type: application/json

{
  "name": "JUANCITO",
  "email": "juancito.mecanico@juan.com",
  "password": "123456"
}

### DELETE user
DELETE  {{baseUrl}}/4
