@baseUrl = http://localhost:3001/v1/

### GET
GET http://localhost:3001/v1/users

### POST /users
POST http://localhost:3001/v1/users
Content-Type: application/json

{
  "name": "Elizatbeth",
  "email": "eli@example.com",
  "password": "123456"
}

### DELETE user

DELETE  http://localhost:3001/v1/users/1
