@baseUrl = http://localhost:3001/v1/

### POST /users
POST http://localhost:3001/v1/users
Content-Type: application/json

{
  "name": "Ho",
  "email": "ho@example.com",
  "password": "123456"
}

### GET

GET http://localhost:3001/v1/users
