@baseUrl = http://localhost:3001/v1/users

### GET
GET {{baseUrl}}

### POST /users
POST {{baseUrl}}
Content-Type: application/json

{
  "Name": "Daniel",
  "Email": "daniel@example.com",
  "Password": "123456",
  "Id_typeUser":10
}

### UPDATE /users
PATCH  {{baseUrl}}/3
Content-Type: application/json

{
  "name": "JUANCITO",
  "email": "juancito.mecanico@juan.com",
  "password": "123456"
}

### DELETE user

DELETE  {{baseUrl}}/1
